config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create]

  resources :products

  root 'products#index'
  # get 'products/index'
  # get '/products', to:'products#index'
  # get '/products/new', to: 'products#new' , as: 'new_product'
  # post '/products', to: 'products#create'
  # get '/products/:id', to: 'products#show', as: 'product'
  # get '/products/:id/edit', to: 'products#edit', as: 'edit_product'
  # patch '/products/:id', to: 'products#update'
  # delete '/products/:id' , to: 'products#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password validations: false #cifrar password al ingresarlo

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @vproducts=Product.all
  end

  def  new

    @product=Product.new

  end

  def create
    @product=Product.new(product_params)
    if @product.save
      redirect_to products_path, notice: "El producto fue publicado con exito"
    else
      render :new
    end
  end

  def show

    @product =Product.find(params[:id])

  end

  def edit

      @product =Product.find(params[:id])

  end

  def update

    @product=Product.find(params[:id])
    if @product.update(product_params)

      redirect_to products_path, notice: "El producto ha sido modificado"
    else

      render :edit
    end

  end

  def destroy

    product=Product.find(params[:id])
    product.destroy

    redirect_to products_path, notice: "el producto se elimino con exito"

  end

  private
    def product_params

      params.require(:product).permit(:name, :url, :description)

    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new

    @user = User.new

  end

  def create
    @user=User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new 
    end
  end

  private
    def user_params

      params.require(:user).permit(:email, :password, :name, :twitter_handle)

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def form_title

    @product.new_record? ? "NUEVO PRODUCTO" : "Modificar producto"

  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Phunter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if flash[:notice] %>
    <div class="alert alert-info">
      <%= flash[:notice] %>

    </div>
  <% end %>

    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">

      <div class="text-center">
        <h1><%= form_title %></h1>

      </div>

      <%= form_for @product do |f| %>

        <div class="form-group">

          <%= f.text_field :name, class: "form-control input-lg",
          placeholder:"Ingresa el nombre" %>

        </div>
        <div class="form-group">

          <%= f.url_field :url, class: "form-control input-lg",
          placeholder:"Ingresa la url" %>

        </div>
        <div class="form-group">

          <%= f.text_area :description, class: "form-control input-lg",
          placeholder:"Ingresa la descripcion del producto" %>

        </div>

        <div class="form-group">

          <%= f.submit form_title, class: "btn btn-primary btn-lg
          btn-block" %>

        </div>


      <% end %>

    </div>
  </div>

</div>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<div class="container">

  <div class="row">

    <div class="col-sm-12">


        <div class="text-center">
                <h1>PRODUCTOS</h1>
        </div>


      <div class="text-right">
        <%= link_to "PUBLICAR PRODUCTO", new_product_path,class: "btn btn-primary btn-sm " %>

      </div>

      <table class="table text center">
        <tr>
          <th>Id</th>
          <th>Nombre</th>
          <th>URL</th>
          <th>DESCRIPTION</th>
        </tr>
        <% @vproducts.each do |p| %>
          <tr>
            <td><%= p.id %></td>
            <td><%= link_to p.name, p %></td>
            <td><%= p.url %></td>
            <td><%= p.description %></td>
            <td>
              <%= link_to "EDITAR", edit_product_path(p) %>
              <%= link_to "ELIMINAR", p , method: :delete, data:{confirm: "¿seguro?"} %>
            </td>

          </tr>
        <% end %>

      </table>

    </div>

  </div>

</div>

app/views/products/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">

      <div class="text-center">
        <h1>NUEVO PRODUCTO</h1>

      </div>

      <%= form_for @product do |f| %>

        <div class="form-group">

          <%= f.text_field :name, class: "form-control input-lg",
          placeholder:"Ingresa el nombre" %>

        </div>
        <div class="form-group">

          <%= f.url_field :url, class: "form-control input-lg",
          placeholder:"Ingresa la url" %>

        </div>
        <div class="form-group">

          <%= f.text_area :description, class: "form-control input-lg",
          placeholder:"Ingresa la descripcion del producto" %>

        </div>

        <div class="form-group">

          <%= f.submit "PUBLICAR", class: "btn btn-primary btn-lg
          btn-block" %>

        </div>


      <% end %>

    </div>
  </div>

</div>

app/views/products/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-sm-12">

      <h1><%= @product.name %></h1>

      <p><%= @product.description %></p>

      <a href="<%= @product.url %>" target="_blank">Obtenlo</a>
      
    </div>

  </div>

</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <h1>Crear Cuenta</h1>

    <%= form_for @user do |f| %>
      <div class="form-group">
        <%= f.email_field :email, class: "form-control input-lg", placeholder: "Email" %>
      </div>

      <div class="form-group">
        <%= f.password_field :password, class: "form-control input-lg", placeholder: "Contraseña" %>
      </div>

      <div class="form-group">
        <%= f.text_field :name, class: "form-control input-lg", placeholder: "Nombre" %>
      </div>

      <div class="input-group input-group-lg">
        <span class="input-group-addon" id="basic-addon1">@</span>
        <%= f.text_field :twitter_handle, class: "form-control input-lg", placeholder: "Twitter" %>
      </div>

      <div class="actions">
        <%= f.submit class: "btn btn-primary btn-block btn-lg" %>
      </div>
    <% end %>
  </div>
</div>
</div>